apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  type: LoadBalancer
  selector:
    app: healthcare
  ports:
    - name: http
      protocol: TCP
      port: 80          # Port exposed to outside world
      targetPort: 8082  # Port inside the container (as seen in describe pod)
      nodePort: 31368   # Custom NodePort (must be between 30000â€“32767)
